apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralbank-db
  labels:
    app: neuralbank-db
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-db
  template:
    metadata:
      labels:
        app: neuralbank-db
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-13:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              value: "{{ .Values.global.postgresql.auth.username }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.global.postgresql.auth.password }}"
            - name: POSTGRESQL_DATABASE
              value: "{{ .Values.global.postgresql.auth.database }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neuralbank-db-pvc